Support batch size and batch quantity in the ES plugin
ozontech/file.d pull request #133
Opened 2022-07-21 21:34 UTC by vadimalekseev

Closes #132

2022-07-22 09:31 UTC, vano144 commented on plugin/output/file/file.go
> +		0,
?

2022-07-22 09:34 UTC, vitkovskii requested changes

2022-07-22 09:34 UTC, vitkovskii commented on pipeline/batch.go
> +	batchSizeBytes      int
Let's use same naming everywhere. `maxSizeBytes/maxSizeCount`, `batchSizeBytes/batchSizeCount` for example

2022-07-25 10:56 UTC, vano144 approved these changes

2022-07-26 10:38 UTC, merged