all: set map len
ozontech/file.d pull request #187
Opened 2022-09-06 11:31 UTC by sashamelentyev

2022-09-06 12:31 UTC, ansakharov requested changes
Please add issue according to: https://github.com/ozontech/file.d/blob/master/CONTRIBUTING.md

2022-09-06 12:31 UTC, ansakharov commented on cfg/config.go
> +
Remove blank line here

2022-09-06 12:31 UTC, ansakharov commented on cfg/config.go
> +
Remove blank line here

2022-09-06 12:38 UTC, sashamelentyev commented
@ansakharov thank you for review!
All done.

2022-09-07 13:46 UTC, ansakharov approved these changes
LGTM.
But issue is empty :(

2022-09-07 13:48 UTC, merged