minifix
ozontech/file.d pull request #202
Opened 2022-09-09 10:55 UTC by DSmolonogov

test TestStartWithMultiBuckets, oft fall on 397 line, i set more friendly time.Sleep. Test began to fall less frequently.

2022-09-12 14:18 UTC, vadimalekseev requested changes
Stop using reflection and unsafe.

2022-09-13 09:57 UTC, vadimalekseev commented on pipeline/pipeline.go
> +			return fmt.Errorf("time passed out test failed")
`return ctx.Err()`

2022-09-13 09:59 UTC, vadimalekseev commented on plugin/output/s3/s3_test.go
> +func newPipeline(t *testing.T, configOutput *Config, objStoreF objStoreFactory, pipelineCapacity int) *pipeline.Pipeline {
1. Why do we need to set the pipelineCapacity? It is always 4096
2. Can we return pipeline.Test from this function?

2022-09-14 12:11 UTC, ansakharov requested changes

2022-09-19 11:30 UTC, closed without merging