change test, add retention_size, minifix config
ozontech/file.d pull request #210
Opened 2022-09-19 15:44 UTC by DSmolonogov

Fixes # 197

2022-10-07 12:46 UTC, ansakharov requested changes

2022-10-07 12:46 UTC, ansakharov commented on plugin/output/file/file.go
> +			timer.Stop()
Why stopping timer? Sealing file rotates with new one

2022-10-07 12:46 UTC, ansakharov commented on pipeline/streamer.go
> -	s.shouldStop.Store(true)
How it stops now?

2022-10-07 12:46 UTC, ansakharov commented on pipeline/streamer.go
> +	s.shouldStop.Store(false)
Why stopping in heartbeat?

2022-10-19 14:52 UTC, vadimalekseev approved these changes

2022-11-10 02:46 UTC, vano144 commented on plugin/output/file/file.go
> +	p.fileIsFully = false
what do you think about move this (initialization of p.fileIsFully and p.fileSize) in createNew ?

2022-11-10 02:48 UTC, vano144 commented on plugin/output/file/file.go
> +	p.nextSealUpTime = time.Now().Add(p.config.RetentionInterval_)
Please add comment why it sould be before check on size

2022-11-10 02:50 UTC, vano144 commented on plugin/output/file/file.go
> +		case <-p.retentionChan:
what about case when both options are on?

2022-11-11 11:24 UTC, ansakharov commented
lgtm

2022-11-11 11:24 UTC, ansakharov approved these changes

2023-04-07 11:16 UTC, vadimalekseev commented
Closed due to exceeding dependency caching quota for open PR

2023-04-07 11:16 UTC, closed without merging