[goreleaser] Setup automated builds for new file.d versions
ozontech/file.d pull request #52
Opened 2022-03-04 14:00 UTC by ssnd

closes #51

2022-03-05 12:41 UTC, anuriq requested changes

2022-03-05 12:41 UTC, anuriq commented on .goreleaser.yml
> +#   skip: true
what does this do?

2022-03-05 12:41 UTC, anuriq commented on .goreleaser.yml
> +      - src: ./releaser/config.yaml
`releaser` dir is best practice?

2022-03-05 12:41 UTC, anuriq commented on releaser/scripts/postinstall.sh
> +  systemctl restart file.d
starting the daemon after installation is not best practice

2022-03-09 13:50 UTC, anuriq approved these changes

2022-03-09 13:50 UTC, anuriq commented
LGTM

2022-03-10 09:25 UTC, vano144 commented
LGTM

2022-03-10 09:25 UTC, vano144 commented
LGTM

2022-03-10 09:25 UTC, merged